# borrowed from: https://github.com/puckel/docker-airflow
version: '3.7'

services:

    airflow_db:
        image: postgres:9.6
        container_name: airflow_db
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5431:5432"

    etl_db:
        image: postgres:9.6
        container_name: etl_db
        environment:
            - POSTGRES_USER=etl
            - POSTGRES_PASSWORD=etl
            - POSTGRES_DB=etl_db
            - PGPASSWORD=etl
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5433:5432"
        volumes:
            - ./sql_dags:/usr/local/airflow/sql_dags
        command: postgres -c log_statement=all

    airflow:
        build: .
        image: marwamc/docker-airflow
        container_name: airflow
        restart: always
        depends_on:
            - airflow_db
            - etl_db
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - PGPASSWORD=etl
            - AIRFLOW_CONN_ETL_DB="postgresql://etl:etl@etl_db:5432/etl_db"
            - PSQL="psql --host etl_db --port 5432 --username=etl --dbname etl_db --echo-errors --echo-queries"
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow_dags:/usr/local/airflow/dags
            - ./sql_dags:/usr/local/airflow/sql_dags
            - ./Makefile:/usr/local/airflow/Makefile
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8086:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 2
